language: node_js
node_js:
  - "7"
deploy:
  fqdn: jonshort.me
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  local_dir: build
  on:
    branch: master
  provider: pages
  skip_cleanup: true
